// config.example.js
const SUPABASE_URL = ' https://klgppqyaobblbkbubqun.supabase.co
';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsZ3BwcXlhb2JibGJrYnVicXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAyNDM2NjIsImV4cCI6MjEwNTgxOTY2Mn0.FZTGmmjF7RfLllAGMzdB3U6NsOEjLO8pfDmfKzlZ3Lg
';
